### ISSUE TITLE
 Error loading script: facefusion_ui.py

### ISSUE THREAD

**Issue by WrathofGod** [er1cw00/sd-webui-facefusion#1]
i get error:
```
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 6, in <module>
        from facefusion.core import apply_args, get_argument_parser, limit_resources, pre_check
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\core.py", line 18, in <module>
        from facefusion.predictor import predict_image, predict_video
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\predictor.py", line 5, in <module>
        import opennsfw2
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
        from ._inference import Aggregation
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\opennsfw2\_inference.py", line 12, in <module>
        from keras import Model  # type: ignore
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
        from keras import __internal__
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__internal__\__init__.py", line 3, in <module>
        from keras.__internal__ import backend
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__internal__\backend\__init__.py", line 3, in <module>
        from keras.src.backend import _initialize_variables as initialize_variables
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\__init__.py", line 21, in <module>
        from keras.src import applications
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\applications\__init__.py", line 18, in <module>
        from keras.src.applications.convnext import ConvNeXtBase
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\applications\convnext.py", line 28, in <module>
        from keras.src import backend
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\backend.py", line 35, in <module>
        from keras.src.engine import keras_tensor
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\engine\keras_tensor.py", line 19, in <module>
        from keras.src.utils import object_identity
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\utils\__init__.py", line 53, in <module>
        from keras.src.utils.feature_space import FeatureSpace
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\utils\feature_space.py", line 20, in <module>
        from keras.src.engine import base_layer
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\engine\base_layer.py", line 43, in <module>
        from keras.src.saving.legacy.saved_model import layer_serialization
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saved_model\layer_serialization.py", line 23, in <module>
        from keras.src.saving.legacy.saved_model import save_impl
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saved_model\save_impl.py", line 32, in <module>
        from keras.src.saving.legacy import saving_utils
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saving_utils.py", line 24, in <module>
        from keras.src import losses
      File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\losses.py", line 1680, in <module>
        @tf.__internal__.dispatch.add_dispatch_support
    AttributeError: module 'tensorflow.python' has no attribute '__internal__'
```

who can help me

**Comment by WrathofGod** [comment]
> i get error:
> 
> ```
> *** Error loading script: facefusion_ui.py
>     Traceback (most recent call last):
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
>         script_module = script_loading.load_module(scriptfile.path)
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
>         module_spec.loader.exec_module(module)
>       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 6, in <module>
>         from facefusion.core import apply_args, get_argument_parser, limit_resources, pre_check
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\core.py", line 18, in <module>
>         from facefusion.predictor import predict_image, predict_video
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\predictor.py", line 5, in <module>
>         import opennsfw2
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\opennsfw2\__init__.py", line 4, in <module>
>         from ._inference import Aggregation
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\opennsfw2\_inference.py", line 12, in <module>
>         from keras import Model  # type: ignore
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
>         from keras import __internal__
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__internal__\__init__.py", line 3, in <module>
>         from keras.__internal__ import backend
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\__internal__\backend\__init__.py", line 3, in <module>
>         from keras.src.backend import _initialize_variables as initialize_variables
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\__init__.py", line 21, in <module>
>         from keras.src import applications
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\applications\__init__.py", line 18, in <module>
>         from keras.src.applications.convnext import ConvNeXtBase
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\applications\convnext.py", line 28, in <module>
>         from keras.src import backend
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\backend.py", line 35, in <module>
>         from keras.src.engine import keras_tensor
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\engine\keras_tensor.py", line 19, in <module>
>         from keras.src.utils import object_identity
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\utils\__init__.py", line 53, in <module>
>         from keras.src.utils.feature_space import FeatureSpace
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\utils\feature_space.py", line 20, in <module>
>         from keras.src.engine import base_layer
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\engine\base_layer.py", line 43, in <module>
>         from keras.src.saving.legacy.saved_model import layer_serialization
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saved_model\layer_serialization.py", line 23, in <module>
>         from keras.src.saving.legacy.saved_model import save_impl
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saved_model\save_impl.py", line 32, in <module>
>         from keras.src.saving.legacy import saving_utils
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\saving\legacy\saving_utils.py", line 24, in <module>
>         from keras.src import losses
>       File "F:\AIImage\stable-diffusion-webui1.7\stable-diffusion-webui\venv\lib\site-packages\keras\src\losses.py", line 1680, in <module>
>         @tf.__internal__.dispatch.add_dispatch_support
>     AttributeError: module 'tensorflow.python' has no attribute '__internal__'
> ```
> 
> who can help me

**Comment by er1cw00** [comment]
Hi @WrathofGod  It should be the issue of import opennsfw2.
you must using another sd-webui-facefusion repo  from https://github.com/diffus-me/sd-webui-facefusion which is facefusion 1.3.1 , 
but my repo is fork from  facefusion 2.1.2,
